name: Build macOS App

on:
  push:
    branches:
      - main # Or your main development branch

jobs:
  build-mac:
    runs-on: macos-latest # Use the latest macOS version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Vue app
      run: npm run build

    - name: Build for macOS (Electron)
      run: npm run electron:build -- --mac # For Electron

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-mac
        path: dist_electron/ 